(cl:in-package ublox_msgs-msg)
(cl:export '(VERSION-VAL
          VERSION
          RESERVED0-VAL
          RESERVED0
          REFSTATIONID-VAL
          REFSTATIONID
          ITOW-VAL
          ITOW
          RELPOSN-VAL
          RELPOSN
          RELPOSE-VAL
          RELPOSE
          RELPOSD-VAL
          RELPOSD
          RELPOSLENGTH-VAL
          RELPOSLENGTH
          RELPOSHEADING-VAL
          RELPOSHEADING
          RESERVED1-VAL
          RESERVED1
          RELPOSHPN-VAL
          RELPOSHPN
          RELPOSHPE-VAL
          RELPOSHPE
          RELPOSHPD-VAL
          RELPOSHPD
          RELPOSHPLENGTH-VAL
          RELPOSHPLENGTH
          ACCN-VAL
          ACCN
          ACCE-VAL
          ACCE
          ACCD-VAL
          ACCD
          ACCLENGTH-VAL
          ACCLENGTH
          ACCHEADING-VAL
          ACCHEADING
          RESERVED2-VAL
          RESERVED2
          FLAGS-VAL
          FLAGS
))