// Generated by gencpp from file detection/det_info.msg
// DO NOT EDIT!


#ifndef DETECTION_MESSAGE_DET_INFO_H
#define DETECTION_MESSAGE_DET_INFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace detection
{
template <class ContainerAllocator>
struct det_info_
{
  typedef det_info_<ContainerAllocator> Type;

  det_info_()
    : emg_stop(0)
    , stop_rate(0)  {
    }
  det_info_(const ContainerAllocator& _alloc)
    : emg_stop(0)
    , stop_rate(0)  {
  (void)_alloc;
    }



   typedef int16_t _emg_stop_type;
  _emg_stop_type emg_stop;

   typedef int16_t _stop_rate_type;
  _stop_rate_type stop_rate;





  typedef boost::shared_ptr< ::detection::det_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::detection::det_info_<ContainerAllocator> const> ConstPtr;

}; // struct det_info_

typedef ::detection::det_info_<std::allocator<void> > det_info;

typedef boost::shared_ptr< ::detection::det_info > det_infoPtr;
typedef boost::shared_ptr< ::detection::det_info const> det_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::detection::det_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::detection::det_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::detection::det_info_<ContainerAllocator1> & lhs, const ::detection::det_info_<ContainerAllocator2> & rhs)
{
  return lhs.emg_stop == rhs.emg_stop &&
    lhs.stop_rate == rhs.stop_rate;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::detection::det_info_<ContainerAllocator1> & lhs, const ::detection::det_info_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace detection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::detection::det_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detection::det_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detection::det_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detection::det_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detection::det_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detection::det_info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::detection::det_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8fe94a38075b37159e1d95c90bacc07a";
  }

  static const char* value(const ::detection::det_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8fe94a38075b3715ULL;
  static const uint64_t static_value2 = 0x9e1d95c90bacc07aULL;
};

template<class ContainerAllocator>
struct DataType< ::detection::det_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "detection/det_info";
  }

  static const char* value(const ::detection::det_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::detection::det_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 emg_stop\n"
"int16 stop_rate\n"
;
  }

  static const char* value(const ::detection::det_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::detection::det_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.emg_stop);
      stream.next(m.stop_rate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct det_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::detection::det_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::detection::det_info_<ContainerAllocator>& v)
  {
    s << indent << "emg_stop: ";
    Printer<int16_t>::stream(s, indent + "  ", v.emg_stop);
    s << indent << "stop_rate: ";
    Printer<int16_t>::stream(s, indent + "  ", v.stop_rate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DETECTION_MESSAGE_DET_INFO_H
