# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from main_msg/jet2ard.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class jet2ard(genpy.Message):
  _md5sum = "66290710e2d0e64ff792d8d065b9d5a8"
  _type = "main_msg/jet2ard"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int64 throttle
int64 brake
int64 stop_sign
time start_time"""
  __slots__ = ['throttle','brake','stop_sign','start_time']
  _slot_types = ['int64','int64','int64','time']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       throttle,brake,stop_sign,start_time

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(jet2ard, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.throttle is None:
        self.throttle = 0
      if self.brake is None:
        self.brake = 0
      if self.stop_sign is None:
        self.stop_sign = 0
      if self.start_time is None:
        self.start_time = genpy.Time()
    else:
      self.throttle = 0
      self.brake = 0
      self.stop_sign = 0
      self.start_time = genpy.Time()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3q2I().pack(_x.throttle, _x.brake, _x.stop_sign, _x.start_time.secs, _x.start_time.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.start_time is None:
        self.start_time = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.throttle, _x.brake, _x.stop_sign, _x.start_time.secs, _x.start_time.nsecs,) = _get_struct_3q2I().unpack(str[start:end])
      self.start_time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3q2I().pack(_x.throttle, _x.brake, _x.stop_sign, _x.start_time.secs, _x.start_time.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.start_time is None:
        self.start_time = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.throttle, _x.brake, _x.stop_sign, _x.start_time.secs, _x.start_time.nsecs,) = _get_struct_3q2I().unpack(str[start:end])
      self.start_time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3q2I = None
def _get_struct_3q2I():
    global _struct_3q2I
    if _struct_3q2I is None:
        _struct_3q2I = struct.Struct("<3q2I")
    return _struct_3q2I
